### ISSUE TITLE
Fix build for Python 3.11 (cliff)

### ISSUE THREAD

**Issue by iMichka** [termius/termius-cli#197]
Hello

Homebrew maintainer here. `termius-cli` fails to build with Python 3.11.

```
  File "/opt/homebrew/Cellar/termius/1.2.15_5/libexec/lib/python3.11/site-packages/cliff/app.py", line 387, in run_subcommand
    if 'cmd_name' in inspect.getargspec(cmd_factory.__init__).args:
                     ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

This was fixed in a newer cliff version: https://github.com/openstack/cliff/commit/075345196d0747168a27d71aae4e3d97c5746907

Can cliff be updated and a  new version `termius-cli` be release?

See https://github.com/Homebrew/homebrew-core/pull/115838 for reference.

**Comment by chemputer** [comment]
What would the point be since it no longer works with the newer encryption methods that Termius uses, rendering the entire termius-cli program useless.

**Comment by iMichka** [comment]
I do not know the details of what you are trying to tell me here. Homebrew has more than 6000 packages and it is sometimes complicated for us maintainers to follow everything that is going on.

Could you please explain me what the issue is with cliff / termius and Python 3.11?

**Comment by chemputer** [comment]
First, thank you for helping maintain Homebrew. I don't use a Mac, but a few of my friends are very thankful it exists, and the few times I've had to use a Mac it was very handy, and package managers in general are just lovely but take a lot of work to maintain the repos.

In short (TLDR version), Termius-CLI has been depreciated by Termius and the functionality that was previously there just doesn't work as it lacks support for a new encryption method used for all the account data they rolled out roughly a year ago. It's dead. No point maintaining it, sadly, unless Termius decides to support this again, which they have had ample time to do, and have not.

Longer explanation: Termius has since switched encryption methods for the account data (your hosts and whatnot), and that new encryption method (which is roughly a year or so old at this point I believe and very few accounts would still be on the old encryption as it pestered you into clicking yes - I honestly can't remember if not upgrading was even an option.) and this new encryption method is not supported by Termius-CLI, and there are no plans to make it so that it does support it, as this was one of, if not the only way you could bulk export your hosts and such from the application, and they don't seem to want that to be possible. People might migrate away.

I don't see the point of wasting the time of a clearly skilled developer to get a depreciated client "working" on the latest Python version, because even when it "works" you can't actually do anything, you log in and get a message saying it doesn't support the new encryption method and that's the extent of the functionality.

I hope that clears it up, if not please let me know if I can clarify anything or provide links or however else I can help.

**Comment by iMichka** [comment]
Ok thanks for the clear explanation. I've read https://github.com/termius/termius-cli/issues/188.

I think we are going to deprecate the tool in Homebrew, which means an automatic removal from Homebrew in roughly 1 year from now. There's nothing else we can do on our side.
